---
engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
- spec/**/*
- lib/mscgen_js/**/*
